image: php:7.2-cli

services:
  - postgres:latest

variables:
  POSTGRES_DB: test_db
  POSTGRES_USER: testrunnner
  POSTGRES_PASSWORD: ""

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
  - vendor/

before_script:
- >
  set -xe
  && apt-get update -yqq
  && apt-get install -yqq
  git
  libicu-dev
  libpq-dev
  libzip-dev
  zlib1g-dev
- >
  docker-php-source extract
  && docker-php-ext-install
  pdo_pgsql
  pgsql
  sockets
  intl
  zip
  && docker-php-source delete
- curl -sS https://getcomposer.org/installer | php
- php composer.phar self-update
- php composer.phar install --no-progress --no-interaction
- cp .env.gitlab-ci .env

test:app:
  variables:
    DB_CONNECTION: pgsql
    DB_HOST: postgres
    DB_PORT: "5432"
    DB_DATABASE: test_db
    DB_USERNAME: testrunnner
    DB_PASSWORD: ""
  script:
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text
